### ISSUE TITLE
Index out of range / AssertionError

### ISSUE THREAD

**Issue by pedronahum** [facebookresearch/starcraft_defogger#5]
Hi,

There are many "reduced" replays that either the input.shape[0] is less than 1 
```
[12-25 10:01:46 data.py:122 ] |  WARNING | Try 0: Exception while featurizing replay /StarCraft/reduced_replays/15/bwrep_hnuu8.tcr.npz.

Traceback (most recent call last):
  File "/StarCraft/starcraft_defogger/data.py", line 117, in _consumer
    res = featurizer(fn)
  File "/StarCraft/starcraft_defogger/conv_lstm_utils.py", line 46, in featurize_reduced
    assert input.shape[0] > 1
AssertionError
```

or where the "feats" is empty.  
```
[12-25 10:02:10 data.py:122 ] |  WARNING | Try 0: Exception while featurizing replay /StarCraft/reduced_replays/1/bwrep_hz8q6.tcr.npz.

Traceback (most recent call last):
  File "/StarCraft/starcraft_defogger/data.py", line 117, in _consumer
    res = featurizer(fn)
  File "/StarCraft/starcraft_defogger/conv_lstm_utils.py", line 40, in featurize_reduced
    input = feats[0]
IndexError: list index out of range
```

And I was wondering if this is something you experienced when you run your experiments in your environment? 

Thanks and Happy Holidays,

**Comment by ebetica** [comment]
Yes, check the troubleshooting section:

https://github.com/facebookresearch/starcraft_defogger/blob/master/README.md#troubleshooting

Happy holidays!
